# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Runs a set of commands using the runners shell
      - name: The Builder
        run: |
          sudo apt install make tar wget curl rpm qemu-utils golang-go genisoimage python2-minimal bison gawk
          git clone https://github.com/microsoft/CBL-Mariner.git
          cd CBL-Mariner
          git checkout 1.0-stable
          cd toolkit
          sudo make iso REBUILD_TOOLS=y REBUILD_PACKAGES=n CONFIG_FILE=./imageconfigs/full.json
          cd ../out/images/full
      
      - name: Upload to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: CBL-Mariner
          path: |
            *.iso

