name: CBL-Mariner Builder

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps: 
      - uses: actions/checkout@v2
        with:
          repository: microsoft/CBL-Mariner
          path: .
     
      - uses: actions/checkout@v2
        with:
          repository: rdp-studio/Build-CBL-Mariner-Custom
          path: custom
      
      - name: Modify
        run: |
          cp -R -u ./custom/* ./
          rm -rf ./custom
        
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
        id: go
      
      - name: Install Remaining Prerequisites
        run: |
          sudo apt-get update
          sudo apt -y install make tar wget curl rpm qemu-utils genisoimage pigz parted
      
      - name: Build
        run: |
          cd toolkit
          sudo make iso REBUILD_TOOLS=y REBUILD_PACKAGES=n CONFIG_FILE=./imageconfigs/full.json
      
      - name: Upload to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: CBL-Mariner
          path: |
            ./out/images/full/*.iso

