name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      
      - name: The Builder
        run: |
          sudo apt install make tar wget curl rpm qemu-utils golang-go genisoimage python2-minimal bison gawk
          git clone https://github.com/microsoft/CBL-Mariner.git
          cd CBL-Mariner
          git checkout 1.0-stable
          cd toolkit
          sudo make iso REBUILD_TOOLS=y REBUILD_PACKAGES=n CONFIG_FILE=./imageconfigs/full.json
          cd ../out/images/full
      
      - name: Upload to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: CBL-Mariner
          path: |
            *.iso

